default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: launchpad_development

test: &test
  <<: *default
  database: launchpad_test

production:
  <<: *default
  database: launchpad
